### ISSUE TITLE
prompt for password to prevent hardcoded passwords

### ISSUE THREAD

**Issue by mabafaba** [ElliottMess/koboloadeRlight#1]
How would you feel about prompting the user for the password instead of giving it as a parameter?
Just because if it's a parameter, people are destined to hardcode (and accidentally share / publish) their kobo passwords (which in a lot of cases could give access to some serious stuff...). 
I'd suggest to prompt for it every time from within the function 

```
pw <- readLine("enter password:" )
```

**Comment by ElliottMess** [comment]
Added
